### ISSUE TITLE
Limit to "Duplicate Random Item Stack"

### ISSUE THREAD

**Issue by Aniko412** [Goorakh/RiskOfChaos#10]
I just "finished" a run by crashing the game as the duplicate effect seemed to think I hadn't enough lens makers glasses. I guess it exceeded some number that the game couldn't handle anymore and just crashed. As I tend to have everything set to completely random (like almost everything weight 1 and repetition reduction 0) that happened twice already in long runs (around 12h). Would it be possible to add a cap in some way so that the effect wouldn't target an item with too many duplicates anymore?

**Comment by Goorakh** [comment]
Hm, just item count shouldn't really cause such issues, do you recall how many you had before it crashed?

But that's absolutely possible, I could see an item blacklist being useful too
This will probably be added in the next update, can't say when that will be though

**Comment by Aniko412** [comment]
> do you recall how many you had before it crashed?

Not really but I guess something around 10-digit numbers. 

Also maybe an option where an item is less likely to get duped the more of it you have.

**Comment by Goorakh** [comment]
Added as of mod version 1.9.0
