### ISSUE TITLE
Incompatibility with Starstorm 2

### ISSUE THREAD

**Issue by Lord600** [Goorakh/RiskOfChaos#11]
[LogOutput.log](https://github.com/Goorakh/RiskOfChaos/files/12525453/LogOutput.log)
Attached is the log above, for some reason the Gouging debuff on the Nemesis Commando character doesn't proc with the mod installed. I have no idea what is causing this but I just thought I'd let you know.

**Comment by Goorakh** [comment]
Thank you very much for reporting
This is fixed in the next mod version.
