### ISSUE TITLE
Twitch integration issues

### ISSUE THREAD

**Issue by darillogangaming** [Goorakh/RiskOfChaos#15]
I've followed the list of instructions in "readme"
put in the command, roc_twitch_login spacebirdlego oauth:(insert token)
I believe I got the right oauth token, the primary streamer key in twitch, if it's something else then it's not clear what that something else is
I constantly get the error of it not being able to connect to twitch client along with an error of network failure or so, even if I'm live on twitch or not.

**Comment by Goorakh** [comment]
You do not use the stream key to log in, you use an authentication token.

There are several ways of getting one, I usually use [this one](https://twitchapps.com/tmi/), but you can find more just by looking up "Twitch oauth token" in any search engine.

**Comment by MasonatorRoblox** [comment]
I tried looking it up to help her and all I could find was twitch developer docs and forum posts which made me very confused, it would help a lot to include that site in the mod description
