### ISSUE TITLE
Suggestion about RoC mod toggle

### ISSUE THREAD

**Issue by Kunjo87** [Goorakh/RiskOfChaos#18]
Hello,

First I'd like to say a big thanks for your work, RoC is a very fun mod !
I don't have any issues with it, just kind of a QoL feature suggestion, sorry in advance if it's the wrong section to post it.

_Suggestion:_ Instead of enabling/disabling the mod in the settings tab, I think it would be a lot more convenient to be able to enable its content directly in the Lobby as a lot of other mods do, either in the **Extension** tab, as an **Artifact** or even in your own additional Tab.

I don't really know how much work that would represent, an Artifact probably more than an Extension and enabling from the lobby would also imply the voting system...

Well, that was my 2 cents suggestion to make your mod even better, thanks again !

Regards.

**Comment by Goorakh** [comment]
Hi!

I have actually considered something like this before, and it would probably be a nice feature for some people. I could see a couple settings potentially getting added to the lobby at some point. Probably not in the near future though.

**Comment by Kunjo87** [comment]
Thank you for your answer !

Glad to hear you thought about a similar feature. I was suggesting it because even if the mod is really good for those fun, chaotic or spicy runs, it definitely correspond to what the Artefact are doing and sometimes I just wish I could enabling it from the lobby instead of going back to the settings. That's not a very big deal though, just some Quality of Life improvement.

Anyway, I'll follow closely the future updates, thanks again for your work and your time spent to make this game more enjoyable for the community !

Regards.
