### ISSUE TITLE
[suggestion] A version of the mod that runs effects only at certain events?

### ISSUE THREAD

**Issue by Darkmega18** [Goorakh/RiskOfChaos#2]
A less constantly chaotic game mode, (possibly as an artifact?) where it runs effects when certain things are done instead of on a timer.

running an effect (or several effects) at the start of the mission.
Running an effect when A Newt shrine is used.
Running an effect when the main teleporter is started.
Running an effect when the tele-boss is killed.
Running an effect when a player is killed.
Running an effect when a pillar/void signal is done.
Running an effect when a void seed goes down.

stuff like that. possibly with some way to to disable particularly nasty stuff. like being sequenced.

**Comment by Goorakh** [comment]
An interesting idea, I'm quite busy nowadays so I doubt I'll be able to implement this any time soon, but I'll keep it in mind for when I do have the time :)

(By the way, have you looked at the config? You can disable and tweak specific effects and also make them happen less frequently, if that's what you're after)

**Comment by Darkmega18** [comment]
ah, I didn't try it yet honestly. I was just making a suggestion for it first cause I can forsee myself getting bullied by it a lot based on the way I play if it's time based. :V
