### ISSUE TITLE
game gets stuck at loading 10%

### ISSUE THREAD

**Issue by pizzaguy6969** [Goorakh/RiskOfChaos#21]
this mod and its dependencies are the only thing i have installed
[LogOutput.log](https://github.com/user-attachments/files/16921831/LogOutput.log)
idk what to do

**Comment by Goorakh** [comment]
The mod has not been updated for SotS, and will not work until it it updated

**Comment by Goorakh** [comment]
Fixed in v2.0.0

**Comment by Goorakh** [comment]
Different issue, but known. A fix is in the works. As a band-aid solution, installing ProperSave should fix it.
