### ISSUE TITLE
Some DLC assets accessible while DLC is disabled or not owned

### ISSUE THREAD

**Issue by Jesright73** [Goorakh/RiskOfChaos#24]
Issue: This mod grants access to some of the DLC without the DLC being owned or enabled by the player. 
Specifically: 
1. The green portal that leads to Prime Meridian, a Seekers of the Storm exclusive stage.
2. Survivors of the Void allies/enemies and effects.
3. Seekers of the Storm exclusive elite aspects.

Why is this an issue? 
Mods should not bypass paywalls, this could lead to takedowns and legal trouble. 
Players who do have the DLC , but have it disabled, likely don't want that content to appear.

Solution: Add a check for ownership of DLC, and whether it is enabled, to determine if the mod can include DLC exclusive content in the randomized effects.

RoR2 v 1.3.5
Risk of Chaos v 2.0.3

**Comment by Goorakh** [comment]
Fixed in v2.1.1
