### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ToxicFrazzles** [Goorakh/RiskOfChaos#3]
I was considering making some changes, but noticed that there's no license on this repo.
As it stands with no license nobody is allowed to modify or use any of the code here https://choosealicense.com/no-permission/ 
Would you consider adding a license or even a license statement to make it clear that nobody is allowed to use this software?

Thanks.

**Comment by Goorakh** [comment]
Ah, I did not intend to lock my code away behind a license, I simply forgot to add that file when I created the repo. Thank you for letting me know :)
