### ISSUE TITLE
Alternate Shitty Icon

### ISSUE THREAD

**Issue by Umbra001** [Goorakh/RiskOfChaos#4]
If you would like to "get rid of that abomination" and replace it with another, I made a quick icon for the mod.
![RiskOfChaos - Mod Icon](https://user-images.githubusercontent.com/128005419/225479899-b53bc6cc-0703-44f1-aa3e-7733fd9eace4.png)

**Comment by Goorakh** [comment]
I honestly didn't think anyone would actually make one, I wrote that bit as a joke in the readme, though I can still save it and keep it around for if I end up wanting to change it or need a variant of the icon :)
