### ISSUE TITLE
Friend cant find config file anywhere

### ISSUE THREAD

**Issue by ComoAsuhDude** [Goorakh/RiskOfChaos#6]
Tried playing this mod in multiplayer, we both downloaded the mod and all dependencies, whenever we launch the game it kicks him out saying the mods are incompatible. I told him to to check what files he has in r2modman config section and it only shows him the effects file and the messages file, no riskofchaos.cfg. Tried uninstalling and installing multiple times and he still cant get the file.

**Comment by Goorakh** [comment]
Are you sure all the dependencies are enabled? If any of them are disabled in r2modman it could prevent the mod from loading.
Also, please send your friends log file here after starting the game with the mod and having it not work. The log file can be found by going into the profile settings, Browse profile folder, then in the BepInEx folder there should be a LogOutput.log file.

**Comment by Goorakh** [comment]
Cannot reproduce
