### ISSUE TITLE
random no gravity

### ISSUE THREAD

**Issue by saintv02** [Goorakh/RiskOfChaos#7]
randomly after i restart to another run i will continue to fly up even without a new effect

**Comment by Goorakh** [comment]
Are you using any other mods?

And please provide the log file.

**Comment by saintv02** [comment]
0187d95b-c4cf-aab3-7235-35ef5eb18b26

**Comment by Goorakh** [comment]
Mod list doesn't tell me much on its own, going to need the log file too. You can find it in your profile's Settings->Copy log file contents to clipboard, and upload it here.

**Comment by saintv02** [comment]
hey how do i upload it it says that its to big to comment

**Comment by Goorakh** [comment]
Upload it somewhere else like Discord or pastebin and link it here, or you could compress it in a zip or something

**Comment by saintv02** [comment]
[Uploading message.txt…]()

**Comment by saintv02** [comment]
[message (1).txt](https://github.com/Goorakh/RiskOfChaos/files/11369087/message.1.txt)

**Comment by saintv02** [comment]
like that?

**Comment by Goorakh** [comment]
Yes, though sadly the log doesn't say much, could you try disabling some of the mods to see which one(s) are causing issues?

**Comment by Goorakh** [comment]
Cannot reproduce
