### ISSUE TITLE
Toggle Mod Off

### ISSUE THREAD

**Issue by ajmhp** [Goorakh/RiskOfChaos#8]
Is there an option to temporarily disable all effects at once? Not disabling each individually, but essentially toggling off the dispatcher or toggling off the effect activation timer. That would be nice.

**Comment by Goorakh** [comment]
Currently this feature is only in the debug build of the mod, only reason I didn't put it in the release build is that I just didn't think anyone wanted to have it. This will be added in the next mod update, whenever that will be.

**Comment by ajmhp** [comment]
That's awesome to hear!

**Comment by Goorakh** [comment]
Feature added as of version 1.8.0
